# Coffee Industry

## 1. Business Understanding

Despite its strengths, the Colombian coffee industry faces significant challenges, particularly related to climate change. In the 2022/23 coffee year, Colombia experienced a 9.1% decrease in coffee production, largely due to unfavorable weather conditions. This marked the third consecutive year of declining output, bringing production levels to their lowest since 2012.

The global coffee market, however, remains robust. As of the 2022/23 coffee year, world coffee production reached 168.2 million bags, with South America accounting for 48.3% of this total. Colombia's contribution, particularly in the Arabica segment, is crucial, but the country must adapt to ongoing environmental challenges to maintain its market position​.


Looking forward, the global coffee production for the 2023/24 coffee year is expected to increase by 5.8%, with Arabica output, including Colombian Milds, projected to rise significantly. This anticipated recovery offers hope for the Colombian coffee sector, provided that adaptive strategies to counteract the effects of climate change are implemented effectively.

*Source:*
- [International Coffee Organization (ICO)](https://icocoffee.org/resources/about-economics-and-statistics/) [Report and Outlook, December 2023](https://icocoffee.org/resources/public-market-information/)

## 2. Data Mining

### Installs

In [41]:
# !pip install 

### Libraries

In [1]:
import numpy as np
import pandas as pd
import os

# Data Profile Reporting Tool
from ydata_profiling import ProfileReport
# To avoid unneeded warning display
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

import time
import datetime
import pycountry

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

### Importing my Functions

In [2]:
from coffee_functions import process_files, clean_and_prepare_dataframe

### Source

#### UN ComTrade Database: Coffee

As the main objective of this analysis is to explore the current dynamics of the coffee industry, I will examine supply, demand, and trade trends from 2017 to mid-2024. The analysis will focus on the top three coffee producers and exporters, Brazil, Vietnam, and Colombia, aiming to uncover opportunities and provide strategic insights into the market.

To achieve this, I extracted data from the [UN ComTrade Database](https://comtradeplus.un.org/), the global trade data platform from the [United Nations](https://www.un.org/). I selected the target countries and exported data related to coffee exports.

**Datasets:**
1. Brazil Trade from 2017-2024
2. Vietnam Trade from 2017-2022
3. Colombia Trade from 2017-2024

**Metadata**
    - [DataDictionary](datasets\UN_Comtrade_Exports_Database\DataDictionary.csv)

### Load the Data

#### Colombia Trade: 2017-2024

In [20]:
exporters_trade_raw = process_files(r"source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters", "ImportsExports_Coffee", (2017, 2024))
exporters_trade_raw.shape

File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2017.csv
File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2018.csv
File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2019.csv
File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2020.csv
File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2021.csv
File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2022.csv
File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2023.csv
File not found: source\datasets\UN_Comtrade_Exports_Coffee\Top_Exporters\ImportsExports_Coffee_2024.csv
No files were processed.


(0, 0)

In [4]:
exporters_trade_raw.head()

TypeCode FreqCode  RefPeriodId  RefYear  RefMonth  Period  ReporterCode  \
0        C        M     20170101     2017         1  201701           170   
1        C        M     20170101     2017         1  201701           170   
2        C        M     20170101     2017         1  201701           170   
3        C        M     20170101     2017         1  201701           170   
4        C        M     20170101     2017         1  201701           170   

  ReporterISO ReporterDesc FlowCode FlowDesc  PartnerCode PartnerISO  \
0         COL     Colombia        X   Export          899        _X    
1         COL     Colombia        X   Export           32        ARG   
2         COL     Colombia        X   Export          533        ABW   
3         COL     Colombia        X   Export           36        AUS   
4         COL     Colombia        X   Export           56        BEL   

  PartnerDesc  Partner2Code Partner2ISO Partner2Desc ClassificationCode  \
0  Areas, nes             0         W00        World                 H5   
1   Argentina             0         W00        World                 H5   
2       Aruba             0         W00        World                 H5   
3   Australia             0         W00        World                 H5   
4     Belgium             0         W00        World                 H5   

  ClassificationSearchCode  IsOriginalClassification  CmdCode  \
0                       HS                      True    90121   
1                       HS                      True    90111   
2                       HS                      True    90121   
3                       HS                      True    90111   
4                       HS                      True    90111   

                                CmdDesc  AggrLevel  IsLeaf CustomsCode  \
0    Coffee; roasted, not decaffeinated          6    True         C00   
1  Coffee; not roasted or decaffeinated          6    True         C00   
2    Coffee; roasted, not decaffeinated          6    True         C00   
3  Coffee; not roasted or decaffeinated          6    True         C00   
4  Coffee; not roasted or decaffeinated          6    True         C00   

  CustomsDesc  MosCode  MotCode    MotDesc  QtyUnitCode QtyUnitAbbr  \
0   TOTAL CPC        0        0  TOTAL MOT            8          kg   
1   TOTAL CPC        0        0  TOTAL MOT            8          kg   
2   TOTAL CPC        0        0  TOTAL MOT            8          kg   
3   TOTAL CPC        0        0  TOTAL MOT            8          kg   
4   TOTAL CPC        0        0  TOTAL MOT            8          kg   

          Qty  IsQtyEstimated  AltQtyUnitCode AltQtyUnitAbbr      AltQty  \
0     1484.84           False               8             kg     1484.84   
1    98202.00           False               8             kg    98202.00   
2      525.00           False               8             kg      525.00   
3   621420.00           False               8             kg   621420.00   
4  2452090.00           False               8             kg  2452090.00   

   IsAltQtyEstimated      NetWgt  IsNetWgtEstimated  GrossWgt  \
0              False     1484.84              False         0   
1              False    98202.00              False         0   
2              False      525.00              False         0   
3              False   621420.00              False         0   
4              False  2452090.00              False         0   

   IsGrossWgtEstimated  Cifvalue    Fobvalue  PrimaryValue  \
0                False       0.0    24999.57      24999.57   
1                False       0.0   393184.36     393184.36   
2                False       0.0     4481.00       4481.00   
3                False       0.0  2443180.34    2443180.34   
4                False       0.0  9986220.53    9986220.53   

   LegacyEstimationFlag  IsReported  IsAggregate  Unnamed: 47  
0                     0       False         True          NaN  
1                     0       False        

### Data Profiling

In [7]:
# These the columns with constant data
coffee_constant_columns = ['TypeCode', 'FreqCode', 'ReporterCode', 'FlowCode', 'Partner2Code', 'Partner2ISO', 'Partner2Desc', 'ClassificationCode', 'ClassificationSearchCode', 'IsOriginalClassification', 'AggrLevel', 'IsLeaf', 'CustomsCode', 'CustomsDesc', 'MosCode', 'MotCode', 'MotDesc', 'QtyUnitCode', 'QtyUnitAbbr', 'IsQtyEstimated', 'AltQtyUnitCode', 'AltQtyUnitAbbr', 'IsAltQtyEstimated', 'IsNetWgtEstimated', 'GrossWgt', 'IsGrossWgtEstimated', 'LegacyEstimationFlag', 'IsReported', 'IsAggregate']
# These highly correlated columns are similar (differing only in the level of detail) or identical to other columns.
coffee_high_correlated_columns = ['Fobvalue', 'RefPeriodId', 'PartnerCode', 'AltQty', 'NetWgt']
# These have a large porcentage of missing values or is an unsupported column
coffee_missing_values_columns = ['Cifvalue', 'Unnamed: 47']
# Coffee exports data columns to drop from dataframe
coffee_columns_to_drop = coffee_constant_columns + coffee_high_correlated_columns + coffee_missing_values_columns 

## 3. Data Wrangling

### Data Cleaning

In [8]:
# Basic Cleaning 
exporters_trade = clean_and_prepare_dataframe(exporters_trade_raw, coffee_columns_to_drop)
exporters_trade.shape

(8510, 12)

In [9]:
exporters_trade.head()

Year  Month  Period ReporterISO ReporterDesc FlowDesc PartnerISO  \
0  2017      1  201701         COL     Colombia   Export        _X    
1  2017      1  201701         COL     Colombia   Export        ARG   
2  2017      1  201701         COL     Colombia   Export        ABW   
3  2017      1  201701         COL     Colombia   Export        AUS   
4  2017      1  201701         COL     Colombia   Export        BEL   

  PartnerDesc  CmdCode                               CmdDesc   Qty_in_kg  \
0  Areas, nes    90121    Coffee; roasted, not decaffeinated     1484.84   
1   Argentina    90111  Coffee; not roasted or decaffeinated    98202.00   
2       Aruba    90121    Coffee; roasted, not decaffeinated      525.00   
3   Australia    90111  Coffee; not roasted or decaffeinated   621420.00   
4     Belgium    90111  Coffee; not roasted or decaffeinated  2452090.00   

   PrimaryValue  
0      24999.57  
1     393184.36  
2       4481.00  
3    2443180.34  
4    9986220.53

#### Missing data (Null values)

In [10]:
# Checking for missing data
exporters_trade.isnull().sum().sort_values(ascending=False)

Year            0
Month           0
Period          0
ReporterISO     0
ReporterDesc    0
FlowDesc        0
PartnerISO      0
PartnerDesc     0
CmdCode         0
CmdDesc         0
Qty_in_kg       0
PrimaryValue    0
dtype: int64

## Exploratory Data Analysis

In [11]:
exporters_trade.columns

Index(['Year', 'Month', 'Period', 'ReporterISO', 'ReporterDesc', 'FlowDesc',
       'PartnerISO', 'PartnerDesc', 'CmdCode', 'CmdDesc', 'Qty_in_kg',
       'PrimaryValue'],
      dtype='object')

### Univariable Analysis

#### Year

In [12]:
exporters_trade['Year'].nunique() # 8 years of data, from 2017 up to 2024

8

In [13]:
exporters_trade['Year'].unique() # All years are included

array([2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=int64)

#### Month

In [14]:
exporters_trade['Month'].nunique() # 12 months per each year

12

In [15]:
exporters_trade['Month'].unique() # All months are included

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

#### Period

In [16]:
exporters_trade['Period'].nunique() # Combination of Year and Month
# Expected output of 91-92 (84 full years plus 7 or 8 up to Jul-Aug 2024), missing 5 periods (from Mar 2024)

86

In [17]:
exporters_trade['Period'].unique()
# Data from Jan 2017 up to Feb 2024, missing last 5 months

array([201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708,
       201709, 201710, 201711, 201712, 201801, 201802, 201803, 201804,
       201805, 201806, 201807, 201808, 201809, 201810, 201811, 201812,
       201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908,
       201909, 201910, 201911, 201912, 202001, 202002, 202003, 202004,
       202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012,
       202101, 202102, 202103, 202104, 202105, 202106, 202107, 202108,
       202109, 202110, 202111, 202112, 202201, 202202, 202203, 202204,
       202205, 202206, 202207, 202208, 202209, 202210, 202211, 202212,
       202301, 202302, 202303, 202304, 202305, 202306, 202307, 202308,
       202309, 202310, 202311, 202312, 202401, 202402], dtype=int64)

In [57]:
#TODO
# Should I download again the files or should I take out 2 months of 2014?

#### ReporterISO

In [18]:
exporters_trade['ReporterISO'].nunique() # Only one code for now, as this dataset is just only Colombia market

1

In [59]:
colombia_trade['ReporterISO'].unique() # Only one code for now, as this dataset is just only Colombia market

array(['COL'], dtype=object)

#### ReporterDesc

In [60]:
colombia_trade['ReporterDesc'].nunique() # Expected output: 1 as this dataset is just Colombia market

1

In [61]:
colombia_trade['ReporterDesc'].unique() # Expected output: Colombia 

array(['Colombia'], dtype=object)

#### FlowDesc

In [62]:
colombia_trade['FlowDesc'].nunique() # Expected number of types of trade (Exports and Imports)

2

In [63]:
colombia_trade['FlowDesc'].unique() # Expected types of trade (Exports and Imports)

array(['Export', 'Import'], dtype=object)

#### PartnerISO

In [64]:
colombia_trade['PartnerISO'].nunique() # Number of countries that have traded with Colombia in those years
# Count of ISO 3 letter country code for trade partners

108

In [65]:
colombia_trade['PartnerISO'].unique() # List of commercial partners (country ISO abbrevations of 3 letters)
# Unexpected: '_X ', 'X2 ', 'S19'
# TODO codes abbrevations match the ISO?

array(['_X ', 'ARG', 'ABW', 'AUS', 'BEL', 'BOL', 'BRA', 'CAN', 'CHL',
       'CHN', 'HKG', 'CRI', 'DNK', 'DOM', 'ECU', 'SLV', 'EST', 'FIN',
       'FRA', 'DEU', 'GRC', 'IND', 'IRN', 'IRL', 'ISR', 'ITA', 'JPN',
       'LBN', 'MYS', 'MEX', 'MAR', 'NLD', 'NZL', 'NOR', 'S19', 'PAN',
       'PRY', 'PER', 'POL', 'PRT', 'KOR', 'ROU', 'RUS', 'SGP', 'ZAF',
       'ESP', 'SWE', 'CHE', 'SYR', 'TUR', 'USA', 'ARE', 'GBR', 'URY',
       'BHR', 'CUW', 'EGY', 'GEO', 'JAM', 'JOR', 'SVN', 'UKR', 'VEN',
       'DZA', 'X2 ', 'NGA', 'SAU', 'SUR', 'MAC', 'CYP', 'ISL', 'ALB',
       'KWT', 'LVA', 'TTO', 'GTM', 'IDN', 'AUT', 'HRV', 'HND', 'LTU',
       'PHL', 'CUB', 'CZE', 'LBY', 'NIC', 'PYF', 'BGR', 'VNM', 'QAT',
       'HUN', 'BGD', 'GUY', 'SWZ', 'TUN', 'OMN', 'SVK', 'THA', 'IRQ',
       'MNG', 'BRB', 'KHM', 'CIV', 'KEN', 'MLT', 'PAK', 'KAZ', 'MUS'],
      dtype=object)

#### PartnerDesc

In [66]:
colombia_trade['PartnerDesc'].nunique() # Number of countries that have traded with Colombia in those years

108

In [67]:
colombia_trade['PartnerDesc'].unique() # List of commercial partners (country names)
# Unexpected: 'Areas, nes' and 'Other Asia, nes'.
# TODO to confirm official name:'China', 'China, Hong Kong SAR' and 'China, Macao SAR' are not duplicates?
# TODO names convention match the ISO?

array(['Areas, nes', 'Argentina', 'Aruba', 'Australia', 'Belgium',
       'Bolivia (Plurinational State of)', 'Brazil', 'Canada', 'Chile',
       'China', 'China, Hong Kong SAR', 'Costa Rica', 'Denmark',
       'Dominican Rep.', 'Ecuador', 'El Salvador', 'Estonia', 'Finland',
       'France', 'Germany', 'Greece', 'India', 'Iran', 'Ireland',
       'Israel', 'Italy', 'Japan', 'Lebanon', 'Malaysia', 'Mexico',
       'Morocco', 'Netherlands', 'New Zealand', 'Norway',
       'Other Asia, nes', 'Panama', 'Paraguay', 'Peru', 'Poland',
       'Portugal', 'Rep. of Korea', 'Romania', 'Russian Federation',
       'Singapore', 'South Africa', 'Spain', 'Sweden', 'Switzerland',
       'Syria', 'Türkiye', 'USA', 'United Arab Emirates',
       'United Kingdom', 'Uruguay', 'Bahrain', 'Curaçao', 'Egypt',
       'Georgia', 'Jamaica', 'Jordan', 'Slovenia', 'Ukraine', 'Venezuela',
       'Algeria', 'Free Zones', 'Nigeria', 'Saudi Arabia', 'Suriname',
       'China, Macao SAR', 'Cyprus', 'Iceland', 'Albani

#### CmdCode

In [68]:
colombia_trade['CmdCode'].nunique() # Expected output 4, for the commodities codes included in this report.

4

In [69]:
colombia_trade['CmdCode'].unique() # Expected commodities codes.

array([90121, 90111, 90122, 90112], dtype=int64)

#### Qty_in_kg

In [70]:
colombia_trade['Qty_in_kg'].nunique()

7299

In [71]:
colombia_trade['Qty_in_kg'].describe()

count    8.510000e+03
mean     6.458959e+05
std      2.651494e+06
min      0.000000e+00
25%      2.510343e+03
50%      2.554350e+04
75%      2.144054e+05
max      4.160708e+07
Name: Qty_in_kg, dtype: float64

In [72]:
colombia_trade['Qty_in_kg'].min()

0.0

In [73]:
colombia_trade['Qty_in_kg'].max()

41607075.0

#### PrimaryValue

In [74]:
colombia_trade['PrimaryValue'].nunique()

8411

In [75]:
colombia_trade['PrimaryValue'].describe()

count    8.510000e+03
mean     2.559473e+06
std      1.075701e+07
min      4.000000e-01
25%      2.316382e+04
50%      1.322495e+05
75%      8.858824e+05
max      1.659228e+08
Name: PrimaryValue, dtype: float64

In [76]:
colombia_trade['PrimaryValue'].min()

0.4

In [77]:
colombia_trade['PrimaryValue'].max()

165922761.84

## Insights:

- The global coffee market is projected to grow as it is driven by increasing coffee consumption, particularly in emerging markets such as Asia-Pacific, where coffee culture is expanding rapidly.

Major Coffee Producing and Consuming Regions:
- Producing Regions: The majority of coffee is produced in developing countries, especially in South America (Brazil, Colombia), Asia (Vietnam, Indonesia), and Africa (Ethiopia).

- Consuming Regions: The largest coffee markets in terms of consumption are in North America, Europe, and increasingly in Asia-Pacific. Europe leads as the largest consuming region, with 3.2 million metric tons (3,186,000 metric tons) consumed.